services:
  kaspa_explorer:
    container_name: kaspa_explorer
    image: supertypo/kaspa-explorer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      API_URI: http://localhost:8000
      API_WS_URI: ws://localhost:8001

  kaspa_rest_server:
    container_name: kaspa_rest_server
    image: kaspanet/kaspa-rest-server:latest
    restart: unless-stopped
    environment:
      KASPAD_HOST_1: kaspad:16110
      SQL_URI: postgresql+asyncpg://postgres:postgres@kaspa_db:5432/postgres
    ports:
      - "127.0.0.1:8000:8000"

  simply_kaspa_socket_server:
    container_name: simply_kaspa_socket_server
    image: supertypo/simply-kaspa-socket-server:unstable
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8000"
    command: -x 20 -s ws://kaspad:17110

  simply_kaspa_indexer:
    container_name: simply_kaspa_indexer
    image: supertypo/simply-kaspa-indexer:latest
    restart: unless-stopped
    command: -u -s ws://kaspad:17110 -d postgresql://postgres:postgres@kaspa_db:5432/postgres

  kaspad:
    container_name: kaspad
    image: supertypo/rusty-kaspad:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:16110:16110"
      - "127.0.0.1:17110:17110"
    volumes:
      - /var/kaspad:/app/data/
    command: kaspad --yes --nologfiles --disable-upnp --utxoindex --rpclisten=0.0.0.0:16110 --rpclisten-borsh=0.0.0.0:17110

  kaspa_db:
    container_name: kaspa_db
    image: postgres:16-alpine
    restart: unless-stopped
    shm_size: 4G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /var/kaspa_db/:/var/lib/postgresql/data/
